### ISSUE TITLE
Scatter Plot Visualization

### ISSUE THREAD

**Issue by kazourak** [farinaleo/ft_dslr#10]
# Feature
Scatter Plot Visualization

# Description
As a data scientist, I want to create a scatter plot, So that I can identify which two features are similar.

# Acceptance Criteria:
- [x] The script should be named scatter_plot.[extension].
- [x] The script should accept the dataset as input.
- [x] The output should be a scatter plot comparing pairs of features, highlighting similar ones.

**Comment by farinaleo** [comment]
### Usage
- Run `python scatter_plot.py <file path>` to see a matrix of graph
- Run `python scatter_plot.py <file path> <x_col> <y_col>` to a single graph for x_col by y_col
- Launch the scatter_plot.ipynb to see all a once and have the answer
