### ISSUE TITLE
Describe Dataset

### ISSUE THREAD

**Issue by kazourak** [farinaleo/ft_dslr#8]
# Feature
Generate Descriptive Statistics

# Description
As a data scientist, I want to generate descriptive statistics for all numerical features in the dataset, So that I can understand the distribution and variability of the data.

# Acceptance Criteria:
- [x] The program should be named describe.[extension].
- [x] The program should accept a dataset file as input.
- [x] The output should include count, mean, standard deviation, min, 25%, 50%, 75%, and max for each numerical feature.

# Output example:

![Image](https://github.com/farinaleo/ft_dslr/assets/109950841/1467e87d-e24c-425c-a6f1-20c24fef0047)

**Comment by farinaleo** [comment]
- [ ] review code
- [ ] deploy in dev
- [ ] close branch

**Comment by farinaleo** [comment]
### Usage
_in srcs/describe_
Launch the associate notebook
Or `python describe.py <file path>`




![Image](https://github.com/farinaleo/ft_dslr/assets/46383251/75b1e785-3c51-43ab-b002-6ce56015ef64)
